version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pc25cw
      POSTGRES_USER: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
