version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pc25cw
      POSTGRES_USER: postgres
    volumes:
      - ./dev/projetos/database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
